CREATE TABLE IF NOT EXISTS AIRCRAFT(
  ID UUID PRIMARY KEY,
  MODEL VARCHAR
);

CREATE TABLE IF NOT EXISTS ARTICLE(
  ID UUID PRIMARY KEY,
  NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS CURRENCY(
  ID BIGSERIAL PRIMARY KEY,
  EXCHANGE_RATE DECIMAL
);

CREATE TABLE IF NOT EXISTS LOCATION(
  ID BIGSERIAL PRIMARY KEY,
  LONGITUDE DECIMAL,
  LATITUDE DECIMAL
);

CREATE TABLE POST(
  ID BIGSERIAL PRIMARY KEY,
  CREATED_AT TIMESTAMPTZ
);

CREATE TABLE comment(
  id BIGSERIAL PRIMARY KEY,
  content TEXT,
  added_by UUID,
  added_at TIMESTAMPTZ,
  post_id INT
);

CREATE TABLE payment(
  id BIGSERIAL PRIMARY KEY,
  status TEXT
);

CREATE TABLE ORDERS(
  ID BIGSERIAL PRIMARY KEY,
  COUNT INT,
  NAME TEXT
);

CREATE TABLE HOUSE(
  ID BIGSERIAL PRIMARY KEY,
  BUILD_IN DATE
);

CREATE TABLE FLIGHT(
  ID BIGSERIAL PRIMARY KEY,
  ARRIVED_AT TIMESTAMPTZ
);

CREATE TABLE PRODUCT(
  ID BIGSERIAL PRIMARY KEY,
  ADDED_AT TIMESTAMPTZ
);

CREATE TABLE COMPLEX_ENTITY(
  ID BIGINT PRIMARY KEY,
  PROPERTIES VARCHAR
);

INSERT INTO COMPLEX_ENTITY(ID, PROPERTIES) VALUES(1, 'key1=value1;key2=value2');

CREATE TABLE CABLE(
  ID BIGSERIAL PRIMARY KEY,
  DIAMETER DECIMAL,
  PRODUCTION_DATE DATE
);

CREATE TABLE PRODUCTION_INFO(
  ID BIGSERIAL PRIMARY KEY,
  MANUFACTURER VARCHAR,
  PRODUCTION_DATE DATE,
  CABLE_ID BIGINT
);

INSERT INTO CABLE(ID, DIAMETER, PRODUCTION_DATE) VALUES(1, 2.2, NOW());
INSERT INTO PRODUCTION_INFO(ID, MANUFACTURER, PRODUCTION_DATE, CABLE_ID) VALUES(1, 'Cisco', NOW(), 1);

CREATE TABLE OFFSET_DATE_TIME_ENTITY(
  ID BIGSERIAL PRIMARY KEY,
  OFFSET_DATE_TIME_FIELD TIMESTAMPTZ
);

CREATE TABLE MY_ORDER(
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR
);

CREATE TABLE ARCHIVE_ORDER(
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR
);

CREATE TABLE COURSE_STUDENT(
  "id" BIGINT PRIMARY KEY,
  "name" TEXT,
  "gpa" DECIMAL,
  "address.city" TEXT,
  "address.country" TEXT
);